export enum Roles {

    ROLE_USER = 1,
    ROLE_READONLY = 2,
    ROLE_ADMIN = 3,
    ROLE_MANAGER = 4,
    ROLE_LEADER = 5,
    ROLE_SUPERVISOR = 6,
    ROLE_AGENT = 7,
    ROLE_ANONYMOUS = 8,
    ROLE_DIRECTOR = 9,
    ROLE_VALIDATOR = 10,
    ROLE_MEMBERS = 11,
    ROLE_SELLERS = 12,
    ROLE_DEVELOPERS = 13,
    ROLE_MAINTAINERS = 14,
    ROLE_REPORTERS = 15,
    ROLE_TESTERS = 16,
    ROLE_REVIEWERS = 17
};


